[build]
# assuming the gutenberg site is in a docs folder, if it isn't you don't need 
# to have a `base` variable but you do need the `publish` and `command`
publish = "public"
command = "gutenberg build"

[build.environment]
# Set the version name that you want to use and Netlify will automatically use it
GUTENBERG_VERSION = "0.4.2"

# The magic for deploying previews of branches
# We need to override the base url with whatever url Netlify assigns to our 
# preview site.  We do this using the Netlify environment variable 
# `$DEPLOY_PRIME_URL`.

[context.deploy-preview]
command = "gutenberg build --base-url $DEPLOY_PRIME_URL"
