---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: site/essays
  label: Essays
  create: all
  match: "**/*.md"
- type: directory
  path: site/journal
  label: Journal
  create: all
  match: "**/*.md"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn serve
